# A&R Analyst Portfolio Project — Part 2
### Live Data: Emerging Artist Momentum Signals

**Prepared by:** Manav Desai

Part 1 established that static audio characteristics have become weaker predictors of hit potential over time. This section shifts to momentum-based signals — using live Spotify search and Last.fm listener/engagement data — to identify artists showing real traction, as a more current approach to scouting.

In [33]:
# Authenticate with Spotify using Client Credentials flow (works for public data, no user login needed)
import os
from dotenv import load_dotenv
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

# Load API keys from .env file
load_dotenv()

client_id = os.getenv("SPOTIFY_CLIENT_ID")
client_secret = os.getenv("SPOTIFY_CLIENT_SECRET")

# Authenticate with Spotify using Client Credentials flow
# (this flow works for accessing public data — no user login needed)
sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
    client_id=client_id,
    client_secret=client_secret
))

print("Spotify connection established")

Spotify connection established

## 1. Testing API Access

Before building the full pipeline, confirming which Spotify endpoints are still accessible for a standard developer app (given the access restrictions discussed below).

In [6]:
# Test basic search functionality (this endpoint should NOT be affected by the Nov 2024 deprecations)
results = sp.search(q='year:2026', type='track', limit=10)
for item in results['tracks']['items']:
    print(item['name'], '-', item['artists'][0]['name'])

hate that i made you love me - Ariana Grande
Janice STFU - Drake
I Knew It, I Knew You - From "Toy Story 5" - Taylor Swift
stupid song - Olivia Rodrigo
Choosin' Texas - Ella Langley

In [10]:
# I'm grabbing the first track from my earlier search results to test what artist-level data is accessible
first_track = results['tracks']['items'][0]
first_artist_id = first_track['artists'][0]['id']
first_artist_name = first_track['artists'][0]['name']

print(f"Testing artist lookup for: {first_artist_name}")

# Pulling the artist's full profile using their Spotify ID
artist_details = sp.artist(first_artist_id)

# Checking exactly which fields are available (expecting popularity, followers, genres)
print("Available artist fields:", list(artist_details.keys()))

# Checking whether track-level popularity is available as an alternative
print("Available track fields:", list(first_track.keys()))
print("Track popularity value:", first_track.get('popularity'))

Testing artist lookup for: Ariana Grande
Available artist fields: ['external_urls', 'href', 'id', 'images', 'name', 'type', 'uri']
Available track fields: ['album', 'artists', 'disc_number', 'duration_ms', 'explicit', 'external_ids', 'external_urls', 'href', 'id', 'is_local', 'is_playable', 'name', 'track_number', 'type', 'uri']
Track popularity value: None

**Finding:** As of 2026, Spotify's Developer API restricts `popularity`, `followers`, and `genres` fields for standard developer-access apps — both at the artist and track level. This reflects policy changes Spotify rolled out in November 2024 and expanded in February 2026, restricting these fields to apps with Extended Access (which requires 250,000+ monthly active users).

**Adaptation:** Since these fields aren't available via Spotify's API, this project uses Spotify's search/catalog endpoints (still accessible) for track discovery and metadata, combined with the Last.fm API for momentum signals (listener counts, play counts, tags) as a substitute data source.

## 2. Last.fm Integration (Momentum Signals)

Since Spotify's API restricts popularity/follower/genre data for standard developer access (see finding above), this project uses Last.fm's API as a substitute source for artist momentum signals — specifically listener counts and play counts.

In [34]:
from dotenv import load_dotenv
import os

# Reloading .env with override=True since the Last.fm key was added after the notebook's initial load_dotenv() call
load_dotenv(override=True)

lastfm_api_key = os.getenv("LASTFM_API_KEY")

# Confirm the key loaded without printing the actual secret value
print("API key loaded:", lastfm_api_key is not None)

API key loaded: True

In [35]:
# Testing the Last.fm connection with a known artist
params = {
    "method": "artist.getInfo",
    "artist": "Ariana Grande",
    "api_key": lastfm_api_key,
    "format": "json"
}

response = requests.get("http://ws.audioscrobbler.com/2.0/", params=params)
data = response.json()

print(data)

{'artist': {'name': 'Ariana Grande', 'mbid': 'f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387', 'url': 'https://www.last.fm/music/Ariana+Grande', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}], 'streamable': '0', 'ontour': '1', 'stats': {'listeners': '4617096', 'playcount': '1184987084'}, 'similar': {'artist': [{'name': 'Jessie J, Ariana Grande & Nicki Minaj', 'url': 'https://www.last.fm/music/Jessie+J,+Ariana+Grande+&+Nicki+Minaj', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}, {'name': 'Madison Beer', 'url': 'https://www.last.fm/music/Madison+Beer', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}, {'name': 'Cynthia Erivo', 'url': 'https://www.last.fm/music/Cynthia+Erivo', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}, {'name': 'Sabrina Carpenter', 'url': 'https://www.last.fm/music/Sabrina+Carpenter', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}, {'name': 'Doja Cat', 'url': 'https://www.last.fm/music/Doja+Cat', 'image': [{'#text': 'https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'small'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/64s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'medium'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/174s/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'large'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'extralarge'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': 'mega'}, {'#text': 'https://lastfm.freetls.fastly.net/i/u/300x300/2a96cbd8b46e442fc41c2b86b821562f.png', 'size': ''}]}]}, 'tags': {'tag': [{'name': 'pop', 'url': 'https://www.last.fm/tag/pop'}, {'name': 'rnb', 'url': 'https://www.last.fm/tag/rnb'}, {'name': 'female vocalists', 'url': 'https://www.last.fm/tag/female+vocalists'}, {'name': 'Ariana Grande', 'url': 'https://www.last.fm/tag/Ariana+Grande'}, {'name': 'american', 'url': 'https://www.last.fm/tag/american'}]}, 'bio': {'links': {'link': {'#text': '', 'rel': 'original', 'href': 'https://last.fm/music/Ariana+Grande/+wiki'}}, 'published': '22 Apr 2010, 15:54', 'summary': 'Ariana Grande-Butera, better known professionally as simply Ariana Grande, is an American singer, songwriter and actress. She is a multi-platinum, Grammy Award-winning recording artist. Born in Boca Raton, Florida, Grande began her career in 2008 in the Broadway musical "13". She rose to prominence for her role as Cat Valentine in the Nickelodeon television series, Victorious (2010–2013) and in its spin-off, Sam & Cat (2013–2014). As she grew interested in pursuing a music career <a href="https://www.last.fm/music/Ariana+Grande">Read more on Last.fm</a>', 'content': 'Ariana Grande-Butera, better known professionally as simply Ariana Grande, is an American singer, songwriter and actress. She is a multi-platinum, Grammy Award-winning recording artist. Born in Boca Raton, Florida, Grande began her career in 2008 in the Broadway musical "13". She rose to prominence for her role as Cat Valentine in the Nickelodeon television series, Victorious (2010–2013) and in its spin-off, Sam & Cat (2013–2014). As she grew interested in pursuing a music career, Grande recorded songs for the soundtrack of Victorious and signed with Republic Records in 2011 after the label\'s executives discovered videos of her covering songs that she uploaded onto YouTube. She released her debut album, Yours Truly, in 2013. A 1950s doo-wop-influenced pop and R&B album, it debuted atop the US Billboard 200 and spawned her first US top-ten single, "The Way", featuring rapper Mac Miller. \n\nGrande\'s second studio album, My Everything (2014), continued the pop-R&B sound of its predecessor and incorporated EDM elements. It topped the Billboard 200 and featured four US top-ten singles: "Problem", "Break Free", "Bang Bang", and "Love Me Harder" featuring The Weeknd, the most of any artist that year. Grande\'s pop-R&B styles extended on her third studio album, Dangerous Woman (2016), which was her first of three consecutive number-one albums in the UK, and spawned top ten hits such as the Grammy nominated title track and "Side to Side". \n\nOn her next two albums, Sweetener (2018) and Thank U, Next (2019), Grande experimented with trap while maintaining her characteristic pop-R&B tones; being projects with her most creative control yet and showing a more personal and vulnerable side, both debuted at number one in several countries and were acclaimed by music critics. The former won a Grammy for Best Pop Vocal Album and spawned the international top three hit "No Tears Left to Cry", while the latter broke several streaming records. Grande became the first solo artist to hold the top three spots on the Billboard Hot 100 simultaneously when "7 Rings", "Break Up with Your Girlfriend, I\'m Bored" and "Thank U, Next" did so in 2019. She is also the first artist to have the lead singles from each of their first six studio albums debut within the top ten in the US.\n\nGrande released her sixth studio album, Positions (2020) with its lead single, "Positions" debuting at number one in the US and the UK simultaneously. The song became her third number one hit in the US following "Stuck With U" in collaboration with Justin Bieber and "Rain On Me", also in collaboration with Lady Gaga. A deluxe version of Positions was released in February 2021, with four new songs and a remix of "34+35" featuring Doja Cat and Megan Thee Stallion. The remix helped the song peak at number two, the highest-charting song credited to three or more female soloist since 2001 when "Lady Marmalade" performed by Christina Aguilera, Mýa, P!nk, and Lil Kim peaked at number one. The album debuted at number one on the Billboard 200, becoming her fifth album to do so. In April 2021, a remix of The Weeknd\'s "Save Your Tears" was released featuring Grande. The song reached number one in both the US Hot 100 and the Canadian Hot 100. It spent a total of 69 weeks in the US charts, becoming one of the ten longest-running songs in that chart since its publication. \n\nIn November 2021, it was announced that Grande would star in the two-part film adaptation of the musical Wicked as Glinda. The first movie released on November 22nd, 2024 to critical acclaim and a worldwide gross of over $750 million, becoming the highest-grossing musical film adaptation of a Broadway musical. Critics praised Grande\'s performance as Glinda and she recieved over 14 major awards and nominations in the Best Supporting Actress category. Wicked: For Good was released on November 21st, 2025.\n\nAriana Grande’s highly anticipated seventh studio album “eternal sunshine" was released on March 8th, 2024. The title is a reference to one of her favourite films, “Eternal Sunshine of the Spotless Mind” which stars Jim Carrey. The album is a concept album inspired by the events of the film. The lead single “yes, and?" was released on January 12, 2024 and debuted at #1 on the Hot 100. eternal sunshine had a debut at #1 on the Global Spotify charts and on the Billboard 200. The album\'s 2nd single  “we can\'t be friends (wait for your love)" also debuted at #1 on the Hot 100. During this album cycle, she collaborated with Mariah Carey, Brandy, Monica, Charli XCX, and Troye Sivan on various remixes. \n\nGrande has received various accolades, including two Grammy Awards, ten VMAs, one Brit Award, two Billboard Music Awards, and three American Music Awards. All seven of Grande\'s full-length albums have been certified platinum by the RIAA. Grande has sold over 90 million records worldwide, making her one of the best-selling music artists of all time. Having amassed 98 billion streams globally as of 2021, Grande is one of the most-streamed artists of all time and became the first female artist to surpass 90 billion streams. She was the most-streamed female artist of the 2010s decade on Spotify and Apple Music, and was the only female artist to reach 3 billion total streams on the latter as of 2019. In 2024, Grande became the first artist to have five albums with multiple songs over a billion streams on Spotify. She is the only artist to debut the lead single from all their studio albums in the Top 10 of the Hot 100. Her signature ponytail hairstyle has become an iconic piece of pop culture iconography. In October 2024, she was named the 9th greatest pop star of the 21st Century by Billboard and was the newest artist on the list. Forbes ranked her amongst the highest-paid celebrities in 2019, and Time named Grande as one of the 100 most influential people in the world in 2016 and 2019. Billboard recognized her as the "Woman of the Year" in 2018. Her song "Thank U, Next" was in Rolling Stone\'s 2021 revision of their 500 Greatest Songs of All Time. In 2023, the magazine included Grande among the 200 Greatest Singers of All Time. Grande was nominated in the 2024 GRAMMY Awards for Eternal Sunshine and the Oscars, SAG Awards, Golden Globes, and BAFTAs for her performance in Wicked: Part 1.\n\nRecording artists who have cited Grande as an influence or inspiration include Billie Eilish, Chappell Roan, Lana Del Rey, Bryson Tiller, Charlie Puth, Sufjan Stevens, Troye Sivan, Zara Larsson, Tate McRae, Madison Beer, Jung Kook, Michelle Zauner of Japanese Breakfast, Giselle of aespa, and Meghan Trainor.\n\nRecently, Grande has been teasing a new full album, "petal", coming out on July 31st, 2026 through Ariana\'s own label, BabyDoll Music. This album marks the start of Ariana effectively owning her own music. <a href="https://www.last.fm/music/Ariana+Grande">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}}

In [36]:
# Confirm the specific fields we need (listener count and play count) are accessible
print("Listeners:", data['artist']['stats']['listeners'])
print("Play count:", data['artist']['stats']['playcount'])

Listeners: 4617096
Play count: 1184987084

## 3. Building the Track Pool

Searching across eight genres to build a varied pool of current tracks, avoiding bias toward any single genre. (Note: Spotify's search endpoint appears to cap results at 10 per request for standard developer access. The "hip hop" and "alternative" genre tags both returned no results — pop, indie, country, rock, r&b, electronic, and folk were used instead to maintain genre diversity.)

In [45]:
# Searching across multiple genres to build a varied pool of current tracks
search_terms = [
    "genre:pop year:2026",
    "genre:indie year:2026",
    "genre:country year:2026",
    "genre:rock year:2026",
    "genre:r&b year:2026",
    "genre:electronic year:2026",
    "genre:folk year:2026",
    "genre:alternative year:2026"
]

all_tracks = []

for term in search_terms:
    results = sp.search(q=term, type='track', limit=10, market='US')
    tracks = results['tracks']['items']
    all_tracks.extend(tracks)
    print(f"'{term}' returned {len(tracks)} tracks")

print(f"\nTotal tracks collected: {len(all_tracks)}")

'genre:pop year:2026' returned 10 tracks
'genre:indie year:2026' returned 10 tracks
'genre:country year:2026' returned 10 tracks
'genre:rock year:2026' returned 10 tracks
'genre:r&b year:2026' returned 10 tracks
'genre:electronic year:2026' returned 10 tracks
'genre:folk year:2026' returned 10 tracks
'genre:alternative year:2026' returned 0 tracks

Total tracks collected: 70

## 4. Enriching with Momentum Data

Looking up each unique artist's Last.fm listener and play counts.

In [46]:
# Extract unique artist names from our track pool (avoiding duplicate Last.fm lookups)
artist_names = list(set(track['artists'][0]['name'] for track in all_tracks))
print(f"Found {len(artist_names)} unique artists")
print(artist_names)

Found 33 unique artists
['kwn', 'Kehlani', 'Bella Kay', 'Bryson Tiller', 'Avery Anna', 'HUGEL', 'pupsies', 'Josh Fawaz', 'Ariana Grande', 'Malcolm Todd', 'Steve Lacy', 'Beyoncé', 'Cameron Whitcomb', 'Noah Kahan', 'Tucker Wetmore', 'Dexter and The Moonrocks', 'Brent Faiyaz', 'beabadoobee', 'Ella Langley', 'mgk', 'PIXY', 'Rainbow Kitten Surprise', 'jigitz', 'Olivia Rodrigo', 'D A N N Y', 'Oliver Tree', 'Motionless In White', 'Tame Impala', 'F3miii', 'Ian Asher', 'Don Toliver', 'Maphra', 'honestav']

In [47]:
import time

# Collect Last.fm listener/playcount stats for each unique artist
artist_stats = []

for name in artist_names:
    params = {
        "method": "artist.getInfo",
        "artist": name,
        "api_key": lastfm_api_key,
        "format": "json"
    }
    
    response = requests.get("http://ws.audioscrobbler.com/2.0/", params=params)
    data = response.json()
    
    # Some smaller/newer artists might not exist in Last.fm's database at all
    if 'artist' in data:
        listeners = int(data['artist']['stats']['listeners'])
        playcount = int(data['artist']['stats']['playcount'])
        artist_stats.append({'artist': name, 'listeners': listeners, 'playcount': playcount})
        print(f"{name}: {listeners:,} listeners, {playcount:,} plays")
    else:
        print(f"{name}: not found on Last.fm")
    
    # Being polite to Last.fm's API — avoid sending requests too fast
    time.sleep(0.5)

kwn: 243,771 listeners, 6,336,419 plays
Kehlani: 1,792,038 listeners, 76,144,100 plays
Bella Kay: 438,705 listeners, 11,318,081 plays
Bryson Tiller: 1,761,284 listeners, 111,020,928 plays
Avery Anna: 95,543 listeners, 1,454,104 plays
HUGEL: 675,559 listeners, 8,744,398 plays
pupsies: 144,875 listeners, 3,441,606 plays
Josh Fawaz: 22,021 listeners, 146,645 plays
Ariana Grande: 4,617,096 listeners, 1,184,987,084 plays
Malcolm Todd: 1,646,529 listeners, 135,418,257 plays
Steve Lacy: 3,237,021 listeners, 303,323,626 plays
Beyoncé: 6,494,338 listeners, 718,545,462 plays
Cameron Whitcomb: 176,172 listeners, 4,234,551 plays
Noah Kahan: 1,681,400 listeners, 215,010,280 plays
Tucker Wetmore: 175,103 listeners, 3,542,182 plays
Dexter and The Moonrocks: 332,222 listeners, 4,807,974 plays
Brent Faiyaz: 2,120,169 listeners, 247,369,592 plays
beabadoobee: 2,747,381 listeners, 345,356,925 plays
Ella Langley: 484,532 listeners, 13,002,579 plays
mgk: 1,091,813 listeners, 43,253,080 plays
PIXY: 277,208 listeners, 7,083,835 plays
Rainbow Kitten Surprise: 1,122,242 listeners, 46,000,102 plays
jigitz: 232,724 listeners, 3,237,473 plays
Olivia Rodrigo: 3,287,911 listeners, 672,410,238 plays
D A N N Y: 36,756 listeners, 280,965 plays
Oliver Tree: 1,649,558 listeners, 49,943,807 plays
Motionless In White: 948,096 listeners, 65,243,361 plays
Tame Impala: 4,553,333 listeners, 442,949,472 plays
F3miii: 525,489 listeners, 4,341,253 plays
Ian Asher: 377,081 listeners, 4,266,170 plays
Don Toliver: 2,645,569 listeners, 300,661,138 plays
Maphra: 54,854 listeners, 785,154 plays
honestav: 90,955 listeners, 2,237,686 plays

In [48]:
# Convert results into a DataFrame, sorted by listener count for easy comparison
artist_df = pd.DataFrame(artist_stats)
artist_df = artist_df.sort_values('listeners', ascending=False).reset_index(drop=True)
display(artist_df)

                      artist  listeners   playcount
0                    Beyoncé    6494338   718545462
1              Ariana Grande    4617096  1184987084
2                Tame Impala    4553333   442949472
3             Olivia Rodrigo    3287911   672410238
4                 Steve Lacy    3237021   303323626
5                beabadoobee    2747381   345356925
6                Don Toliver    2645569   300661138
7               Brent Faiyaz    2120169   247369592
8                    Kehlani    1792038    76144100
9              Bryson Tiller    1761284   111020928
10                Noah Kahan    1681400   215010280
11               Oliver Tree    1649558    49943807
12              Malcolm Todd    1646529   135418257
13   Rainbow Kitten Surprise    1122242    46000102
14                       mgk    1091813    43253080
15       Motionless In White     948096    65243361
16                     HUGEL     675559     8744398
17                    F3miii     525489     4341253
18              Ella Langley     484532    13002579
19                 Bella Kay     438705    11318081
20                 Ian Asher     377081     4266170
21  Dexter and The Moonrocks     332222     4807974
22                      PIXY     277208     7083835
23                       kwn     243771     6336419
24                    jigitz     232724     3237473
25          Cameron Whitcomb     176172     4234551
26            Tucker Wetmore     175103     3542182
27                   pupsies     144875     3441606
28                Avery Anna      95543     1454104
29                  honestav      90955     2237686
30                    Maphra      54854      785154
31                 D A N N Y      36756      280965
32                Josh Fawaz      22021      146645

## 5. Classifying Artists by Momentum Tier

Using natural breaks in the listener-count distribution to classify artists into three tiers: Established, Emerging, and Early-Stage.

In [49]:
def classify_artist(listeners):
    if listeners >= 1_000_000:
        return 'Established'
    elif listeners >= 100_000:
        return 'Emerging'
    else:
        return 'Early-Stage'

artist_df['tier'] = artist_df['listeners'].apply(classify_artist)
display(artist_df)

                      artist  listeners   playcount         tier
0                    Beyoncé    6494338   718545462  Established
1              Ariana Grande    4617096  1184987084  Established
2                Tame Impala    4553333   442949472  Established
3             Olivia Rodrigo    3287911   672410238  Established
4                 Steve Lacy    3237021   303323626  Established
5                beabadoobee    2747381   345356925  Established
6                Don Toliver    2645569   300661138  Established
7               Brent Faiyaz    2120169   247369592  Established
8                    Kehlani    1792038    76144100  Established
9              Bryson Tiller    1761284   111020928  Established
10                Noah Kahan    1681400   215010280  Established
11               Oliver Tree    1649558    49943807  Established
12              Malcolm Todd    1646529   135418257  Established
13   Rainbow Kitten Surprise    1122242    46000102  Established
14                       mgk    1091813    43253080  Established
15       Motionless In White     948096    65243361     Emerging
16                     HUGEL     675559     8744398     Emerging
17                    F3miii     525489     4341253     Emerging
18              Ella Langley     484532    13002579     Emerging
19                 Bella Kay     438705    11318081     Emerging
20                 Ian Asher     377081     4266170     Emerging
21  Dexter and The Moonrocks     332222     4807974     Emerging
22                      PIXY     277208     7083835     Emerging
23                       kwn     243771     6336419     Emerging
24                    jigitz     232724     3237473     Emerging
25          Cameron Whitcomb     176172     4234551     Emerging
26            Tucker Wetmore     175103     3542182     Emerging
27                   pupsies     144875     3441606     Emerging
28                Avery Anna      95543     1454104  Early-Stage
29                  honestav      90955     2237686  Early-Stage
30                    Maphra      54854      785154  Early-Stage
31                 D A N N Y      36756      280965  Early-Stage
32                Josh Fawaz      22021      146645  Early-Stage

## 6. Engagement Ratio: A Second Momentum Signal

Raw listener count alone doesn't capture fan loyalty. Calculating plays-per-listener surfaces artists with unusually devoted audiences, regardless of tier.

In [50]:
# Calculate plays-per-listener as an engagement/loyalty signal, independent of raw listener count
artist_df['plays_per_listener'] = (artist_df['playcount'] / artist_df['listeners']).round(1)
display(artist_df.sort_values('plays_per_listener', ascending=False))

,artist,listeners,playcount,tier,plays_per_listener
1,Ariana Grande,4617096,1184987084,Established,256.7
3,Olivia Rodrigo,3287911,672410238,Established,204.5
10,Noah Kahan,1681400,215010280,Established,127.9
5,beabadoobee,2747381,345356925,Established,125.7
7,Brent Faiyaz,2120169,247369592,Established,116.7
6,Don Toliver,2645569,300661138,Established,113.6
0,Beyoncé,6494338,718545462,Established,110.6
2,Tame Impala,4553333,442949472,Established,97.3
4,Steve Lacy,3237021,303323626,Established,93.7
12,Malcolm Todd,1646529,135418257,Established,82.2
15,Motionless In White,948096,65243361,Emerging,68.8
9,Bryson Tiller,1761284,111020928,Established,63.0
8,Kehlani,1792038,76144100,Established,42.5
13,Rainbow Kitten Surprise,1122242,46000102,Established,41.0
14,mgk,1091813,43253080,Established,39.6
11,Oliver Tree,1649558,49943807,Established,30.3
18,Ella Langley,484532,13002579,Emerging,26.8
23,kwn,243771,6336419,Emerging,26.0
19,Bella Kay,438705,11318081,Emerging,25.8
22,PIXY,277208,7083835,Emerging,25.6
29,honestav,90955,2237686,Early-Stage,24.6
25,Cameron Whitcomb,176172,4234551,Emerging,24.0
27,pupsies,144875,3441606,Emerging,23.8
26,Tucker Wetmore,175103,3542182,Emerging,20.2
28,Avery Anna,95543,1454104,Early-Stage,15.2
21,Dexter and The Moonrocks,332222,4807974,Emerging,14.5
30,Maphra,54854,785154,Early-Stage,14.3
24,jigitz,232724,3237473,Emerging,13.9
16,HUGEL,675559,8744398,Emerging,12.9
20,Ian Asher,377081,4266170,Emerging,11.3
17,F3miii,525489,4341253,Emerging,8.3
31,D A N N Y,36756,280965,Early-Stage,7.6
32,Josh Fawaz,22021,146645,Early-Stage,6.7

In [51]:
# Save the enriched artist dataset so Part 3 can use it without re-running the API pipeline
artist_df.to_csv('data/emerging_artists.csv', index=False)
print("Saved to data/emerging_artists.csv")

Saved to data/emerging_artists.csv

**Takeaway:** Motionless In White (Emerging tier, 948K listeners) shows a plays-per-listener ratio of 68.8 — the highest in the entire dataset, exceeding even Established artists like Rainbow Kitten Surprise (41.0) and mgk (39.6). This suggests an unusually loyal, highly-engaged fanbase relative to audience size — a potential signal of untapped growth potential ahead of wider audience exposure.

## Summary & Next Steps

This section demonstrates a momentum-based scouting approach, built to work around Spotify's 2024–2026 API access restrictions on popularity/follower/genre data. Combining Spotify search (track discovery across 8 genres) with Last.fm (listener/engagement data) surfaces a data-driven shortlist of 33 unique artists — 15 Established, 13 Emerging, 5 Early-Stage — worth scouting, beyond what raw popularity alone would suggest.

**Next steps:** Develop a combined scoring model integrating these momentum signals with the historical hit-characteristics findings from Part 1 (see Part 3).